### PR TITLE
Add dracula theme

### LINKED ISSUE #1: How to contribute?
Hello @Siedlerchr 

A few months ago I had developed the dracula theme for JabRef - if possible by any chance, I'd like to contribute it here.

[Link to my repository](https://github.com/mai-space/theme-jabref-dracula)

Best regards!

Joël

### PR DESCRIPTION
**Pull request by mai-space**
Resolves: #1

### CODE REVIEW

**Comment by mai-space** [comment]
This adds the current version of my dracula theme. I will update it maybe in the future, but until then, this is my contribution :)

**Comment by Siedlerchr** [comment]
Would be nice if you coud add the other files, screenshot etc as well

**Comment by mai-space** [comment]
Sure thing - Do you need a specific structure?

**Comment by Siedlerchr** [comment]
No, just putt all in your theme folder as you did in your repo.

**Comment by mai-space** [comment]
@Siedlerchr Done :)

**Review by Siedlerchr — APPROVED** [review]

**Comment by mai-space** [comment]
Thank youuuu

**Comment by Siedlerchr** [comment]
We have to thank you! https://themes.jabref.org/ links to the directory with themes.

**Pull request merged**
